spring:
  application:
    name: testing-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        tool:
          hbm2ddl: debug
lolomo:
  initialize-shows: false
